### ISSUE TITLE
Better handling for stream errors?

### ISSUE THREAD

**Issue by gjtorikian** [alpacahq/alpaca-trade-api-go#48]
Today I received the following error while reading streams:

```
polygon stream read error (websocket: close 1006 (abnormal closure): unexpected EOF)
```

Although the library does attempt to reconnect with `s.conn = openSocket()`, this does not set any of the channels (as `Subscribe`) does, so nothing actually happens.

Since this is just a printed message, and not, for example, a returned `err` value, I can't act on it. I would prefer to reconnect to my established channels on an error like this. Do you have any suggestions on how this can be done? I am not certain the current code will allow for it.

**Comment by umitanuki** [comment]
I see so the reconnection logic should reset all auth/subscription. Potentially you should also be able to receive error by returned value or by registering custom error handler?

**Comment by gjtorikian** [comment]
> by registering custom error handler?

Yes, exactly! I think that is how the old NATS logic worked. 

To be honest I am also not sure why this error even comes up (two days in a row now).

**Comment by gjtorikian** [comment]
The error is very similar to https://github.com/gorilla/websocket/issues/321.

**Comment by umitanuki** [comment]
It could be due to the client side consumption is not fast enough that the server side buffer exceeds certain threshold and disconnects from their side. not sure if this particular indicates it or not.

**Comment by saaib** [comment]
Hi @umitanuki , this topic of 'buffer exceeds and not been able to read too fast" is like talking about Godzilla, everyone knows about it, but nobody knows if it exists.

Can someone please post real technical information about that such buffer and timeouts I have requested it many times on slack and the information has not been provided.

I've got the same error every day, it is nearly impossible to have an algo to complete from market open to close without this issue. This is showing no business viability for a real production roll-out unless you blindly restart your script because you catch an exception, which is very generic and the incorrect way to handle the situation.

Regards,

**Comment by siran** [comment]
I've have disconnect problem, and stop receiving quote updates. The error does not raise an exception that I can catch from my algo. My solution has been to make my algo resilient to restarts, and then restarting the algo every 5min. It's a desperation based 'solution'. BTW, I'm not working with Go, but with Python. But also receive the disconnects ofter.

**Comment by ttt733** [comment]
Working on this issue now. Regarding the frequency of disconnects, if it is the Polygon stream that you're being disconnected from more frequently than you think you should, you can let them know at support@polygon.io - we don't have many more details on that than Hitoshi has given. However, the library should be able to handle reconnection much more gracefully. (Since @siran referenced the Python library, Python has some "uniqueness" that makes it more difficult. Go doesn't have those difficulties - I just assumed that what was present for the Alpaca stream would work for the Polygon one, and that's clearly not the case.)

**Comment by ttt733** [comment]
The new code should resubscribe on reconnection as expected. Additionally, users are reporting fewer disconnects across several SDKs, so hopefully disconnects will be less prevalent anyhow.

**Comment by gjtorikian** [comment]
Indeed--I no longer see any disconnects myself. Thanks again!
